version: "3"
services:
  pyatv-mqtt-bridge:
    container_name: pyatv-mqtt-bridge
    image: sebbo2002/pyatv-mqtt-bridge
    restart: always
    network_mode: "host"
    volumes:
      - ./config.json:/app/config.json:ro # First copy, customize and save config.example.json sample file as config.json
    command: pyatv-mqtt-bridge /app/config.json # Default mode
    # command: pyatv-mqtt-bridge --debug /app/config.json # <- Use this line instead for debug mode, then run :
    # docker-compose up
    # to watch the detailed logs
